### ISSUE TITLE
Feature: User can Search

### ISSUE THREAD

**Issue by sharon-tieu** [sharon-tieu/ajax--project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged? 

- User is able to search Ghibli characters, locations, and species. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

1. User will be able to see the search page-view.
2. User will be able to utilize search bar to search Ghibli characters, locations, and species.
3. User will be able to **view search results**
4. User will be able to **view details of search result(s)**

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
<img width="780" alt="Screen Shot 2022-09-25 at 11 15 13 PM" src="https://user-images.githubusercontent.com/103021766/192205902-bc5cf013-673d-47d0-a6b0-0bd93ba2ded5.png">
<img width="780" alt="Screen Shot 2022-09-25 at 11 15 19 PM" src="https://user-images.githubusercontent.com/103021766/192205915-1f51fef0-c549-4b04-80b3-279e3e32a2a0.png">
<img width="664" alt="Screen Shot 2022-09-26 at 12 39 55 AM" src="https://user-images.githubusercontent.com/103021766/192220098-cb2b1da6-97b8-4d44-b9bc-ae77af381e43.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Create a **`search page-view`**.
- [ ] Create a **`search tab`** in the **navigation bar.**
- [ ] Create a `search bar` on the page.
- [ ] Create **`placeholder text`** in the search bar.
- [ ] Create a `dummy structure` in the HTML for the search results.
- [ ] Create a **`DOM tree`** to build a dynamic structure for population. 
- [ ] `Populate` search results. The search result should be the movie title.
- [ ] **Transition:** Make the movie title move slightly up alongside the y-axis of the screen when user hovers over image. 
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by sharon-tieu** [comment]
This can be combined with the issue: User can View Search Details.
