### ISSUE TITLE
Design Update: User can View Home Page

### ISSUE THREAD

**Issue by sharon-tieu** [sharon-tieu/ajax--project#2]
## ⚙️ Feature

> ##### Which feature is affected by this update?

- User can **view Home page**

## 📐 Plan

> ##### Summary of the technical approach to be taken.

1. Create a < div > for a **container**.
2. Create a **row** for the navigation bar.
3. Create two **half-columns** of the navigation bar row.
4. Use **flex-direction** for each of the items located in the navigation bar.
5. Create a text-box and center it with text content.
6. Use **z-index** to incorporate the transparent png to lay on top of the text-box.
7. Style the png transparent file to have animation of moving slightly up along the y-axis when user hovers their mouse over.
8. Style the home in the navigation bar to change colors when user hovers over the tab.

## 🖼️ Wireframes

> ##### Updated wireframe(s) of what the app should look like when the updates are ready.

<img width="849" alt="Screen Shot 2022-09-26 at 5 43 54 PM" src="https://user-images.githubusercontent.com/103021766/192405667-e815c25d-4bf1-4074-b132-9f71022967d8.png">
<img width="849" alt="Screen Shot 2022-09-26 at 5 44 07 PM" src="https://user-images.githubusercontent.com/103021766/192405683-c5e9a25e-134c-4445-a607-97b10f3d53e3.png">
<img width="368" alt="Screen Shot 2022-09-26 at 5 49 25 PM" src="https://user-images.githubusercontent.com/103021766/192406142-1267afa9-dc0d-4e85-a5eb-0ca44d1e56d0.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a `div` for a **container**.
- [x] Create a `row` for the navigation bar.
- [x] Create two `half-columns` of the navigation bar row.
- [x] Use **flex-direction** for each of the items located in the navigation bar.
- [x] Create a `row` for the main content of the browser.
- [x] Create a text-box to hold text content.
- [x] **OPTIONAL CHALLENGE:** Use **`z-index`** to incorporate the transparent png to lay on top of the text-box. If not, then just align the dragon image to the right!
- [x] Style the png transparent file to have `animation` of moving slightly up along the y-axis when user hovers their mouse over.
- [x] Style the home in the navigation bar to `change colors when user hovers` over the tab.
- [x] Dragon png image should "float"/move: Use **`transform: translateY`** to make image move when User's mouse hovers.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that don't do anything.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
