### ISSUE TITLE
Feature: User can View search results 3

### ISSUE THREAD

**Issue by sharon-tieu** [sharon-tieu/ajax--project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

- User can **view the result details** of what they search up.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

1. Once User clicks on the results, User is able to view details.
2. Make a new row with half-columns: One for the text content and the other for the movie title.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Create another row with two column-half's.
- [ ] Make one column-half for text content.
- [ ] Build a DOM tree with the structure shown in the example.
- [ ] Render the information that User searches up in the text box.
- [ ] Build a DOM tree for the movie title to be shown on the right half-column.
- [ ] Create a for-loop to target what the user searched.
- [ ] Create a for-loop to target the movie title of what User searched is from.
- [ ] Render the movie title of where the character, location, or species is found in.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
