### ISSUE TITLE
Feature: User can Like a search result

### ISSUE THREAD

**Issue by sharon-tieu** [sharon-tieu/ajax--project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

- In this feature, User is able to like a card of information. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

1. User is able to "like" a card of information by clicking on a heart icon that appears next to the name of the search result.
2. Use [fontawesome heart icons](https://fontawesome.com/icons/heart?s=solid&f=classic) to code a heart beside the Title of the card. Default should be an empty heart.
3. When user clicks on the heart, the icon should change to a filled out heart. 
4. To keep track of what the User has liked, use a **new array** for liked items.
 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="725" alt="Screen Shot 2022-09-25 at 11 46 21 PM" src="https://user-images.githubusercontent.com/103021766/192210648-6ec6a47d-d963-44d6-89eb-6194487218bc.png">
<img width="725" alt="Screen Shot 2022-09-25 at 11 46 27 PM" src="https://user-images.githubusercontent.com/103021766/192210659-8690418a-af20-4f70-9c44-e346856d50ee.png">
<img width="672" alt="Screen Shot 2022-09-26 at 12 45 19 AM" src="https://user-images.githubusercontent.com/103021766/192221276-d35a3a6b-9feb-4af6-9afe-932978cc99eb.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a `div[page-view="search-results"]` to the HTML.
- [x] Within the `DOM tree`, create a dynamic HTML structure to include the _heart icon_:
- [x] Create a `column` within the title of the card.
- [x] Use `**flex-end**` on the heart icon
- [x] Heart icon should change to a filled-out heart when user clicks "like".
- [x] Make sure the navigation items `transition` to different colors still when User hovers over them.
- [x] Be sure to change the **`page-view`** to its corresponding navigation-bar item when user clicks one of them from the page.
- [x] Create a **`new array`** to keep track of liked items.
- [x] Make sure that each item in this array is given a **`card-id` attribute** to indicate which card it is.
- [x] Create a `**localStorage**` for the User's likes.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
