### ISSUE TITLE
Feature: User can View likes

### ISSUE THREAD

**Issue by sharon-tieu** [sharon-tieu/ajax--project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

- User can view a list of their likes. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

1. User will be able to click "likes" from the navigation bar to view what they have liked so far.
2. User will be able to view a list of their liked items.
3. The 3 liked items per row will appear on the browser.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="777" alt="Screen Shot 2022-09-25 at 11 58 23 PM" src="https://user-images.githubusercontent.com/103021766/192212743-b87decd9-f380-4c24-9194-97d38084a31b.png">
<img width="317" alt="Screen Shot 2022-09-26 at 12 49 56 AM" src="https://user-images.githubusercontent.com/103021766/192222119-2f837c5d-85d1-48ab-a49d-0db927da7ac6.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a new `navigation-bar item`: likes. 
- [x] Create a new **`page-view[likes-list]`**.
- [x] **Transition:** When User hovers mouse over _likes_ from the navigation-bar, it should change colors.
- [x] Create **`likes`** page title to allow User to know that they are on the likes page.
- [x] Utilize the **`liked-items** **array`** to `populate` every item the User has liked.
- [x] Populate User's liked items. 3 cards per row should appear on the browser.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Make sure that each of the navigation items are still able to change its view from this page.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
