### ISSUE TITLE
Feature: User can Unlike

### ISSUE THREAD

**Issue by sharon-tieu** [sharon-tieu/ajax--project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

- Remove or Unlike an item that they have liked from their like list. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

1. User will view a list of their liked items.
2. User can click on the heart icon next to the card's title to "Unlike."
3. Once unliked, a modal will appear on the screen for confirmation.
4. No option should show User's likes list again.
5. Yes option should remove the card item from likes list. 
6. Card item should be removed once User unlikes it.
7. Or a page view that will indicate there is no likes when User unlikes the last item from likes list.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-10-03 at 10 13 03 PM](https://user-images.githubusercontent.com/103021766/193740020-856cc06d-bacd-4720-8365-b912c67616a6.png)
![Screen Shot 2022-10-03 at 10 13 12 PM](https://user-images.githubusercontent.com/103021766/193740026-3a9b7678-ed23-426b-a695-7f664d2a417e.png)
![Screen Shot 2022-10-03 at 10 13 23 PM](https://user-images.githubusercontent.com/103021766/193740037-2d0cafdd-27ef-4bfc-9114-4ba77960add1.png)
![Screen Shot 2022-10-03 at 10 12 42 PM](https://user-images.githubusercontent.com/103021766/193740077-183b2579-6e75-45bf-921d-de6c883319ba.png)

![Screen Shot 2022-10-03 at 10 13 23 PM](https://user-images.githubusercontent.com/103021766/193740128-9d03e208-6e9f-421e-af37-a564c1b9d7c0.png)
![Screen Shot 2022-10-03 at 10 15 32 PM](https://user-images.githubusercontent.com/103021766/193740133-b7238e39-ee13-4d4a-9caa-6108edebe04a.png)
![Screen Shot 2022-10-03 at 10 13 29 PM](https://user-images.githubusercontent.com/103021766/193740143-6fa6de0d-9422-40d1-a3af-756621639e4e.png)
![Screen Shot 2022-10-03 at 10 12 07 PM](https://user-images.githubusercontent.com/103021766/193740155-30ba5958-9b4f-420c-95e6-c1997ca69a58.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add an **`eventListener`** to the heart icon.
- [x] Change the heart to empty when User clicks.
- [x] Create a `modal` with Two buttons:
- [x] `No`: return to likes list page view with the heart icon filled.
- [x] `Yes`: will also return the likes list page view but with the card item removed.
- [x] `Iterate` through the **`likes array`** to find the item User clicks on.
- [x] Use the **`delete method`** on the card item to be removed from the **`likes array`**.
- [x] Make sure that the unliked item is removed from the likes list immediately without refreshing.
- [x] Make sure that the other liked items still appear on the likes list.
- [x] If the **`likes array`** is `empty`, then the likes list page should see a message that says "ごめん(なさい)！
oops! there are no items in your likes list."
- [x] Make sure that all items in the navigation bar are clickable and will change the view when clicked from current page.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
