### ISSUE TITLE
Feature: User can View Search Details

### ISSUE THREAD

**Issue by sharon-tieu** [sharon-tieu/ajax--project#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

1. User can use a search bar to search Ghibli characters.
2. Search results will show details of the character including age, gender, eye color, hair color, and species. 
3. Movie film image of where the character is from will also appear.
4. User can only search one at a time. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="796" alt="Screen Shot 2022-09-28 at 12 05 40 PM" src="https://user-images.githubusercontent.com/103021766/192885778-3c653fca-c146-4cb0-848e-d5fb0acedb4f.png">
<img width="906" alt="Screen Shot 2022-09-28 at 12 08 20 PM" src="https://user-images.githubusercontent.com/103021766/192885805-e462b680-6ae6-4f7c-a93f-8f0c7b0e89f1.png">
<img width="360" alt="Screen Shot 2022-09-28 at 12 13 45 PM" src="https://user-images.githubusercontent.com/103021766/192885827-aa088519-0d44-4516-a413-2239e3001596.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Navigation menu: Create a search item.
- [x] Create a `data-view[search]`
- [x] Create dummy entries in the `HTML` to structure how you want information to be appended.
- [x] Create `DOM Tree` to dynamically build the html with the information.
- [x] Include xhr `'GET'` request from the api. 
- [x] Make `textContent` into an `empty string` after each search for results to only be shown one at a time.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by sharon-tieu** [comment]
https://user-images.githubusercontent.com/103021766/192886155-7e71e707-a1c6-420c-a6c5-f47311c8f8de.mov
